### ISSUE TITLE
Configuration Scanner Overzealous On Identifying Databases

### ISSUE THREAD

**Issue by SattaiLanfear** [flyway/flyway-play#21]
I've encountered a few... explosive failures when trying to use flyway-play while configuring pools and having other extra information in the db configuration section.

The [Play Configuration Reference](https://playframework.com/documentation/2.4.x/SettingsJDBC#Reference) shows that many non-db entries can be present.  Throwing an exception whenever one is encountered seems extreme, and also prejudices against other libraries making use of the space.

I initially encountered this while trying to write my own play adapter for postgresql-async (which admittedly isn't correct at handling this either at the time of this writing).  For its configuration I'd decided that db.asyncPool should contain information configuring the async connection pool and hoped that my lib and this one could coexist nicely.

I think ideally this module should scan, searching for valid urls and drivers, and if it finds one but not the other, consider it an error, otherwise just log that the entry was skipped.  Possibly the addition of a "db.name.flyway" boolean parameter, defaulting to true would allow silencing the logs or explicitly skipping the processing of unwanted database connections.

I'm wrapped up in my own fixes right now or I'd try to submit a patch.

**Comment by tototoshi** [comment]
Fixed in https://github.com/flyway/flyway-play/commit/cf9c24c9ffb232f411b4a6c19a752c9e32191859
