### ISSUE TITLE
By using this plugin, can we still run the Flyway SBT tasks.

### ISSUE THREAD

**Issue by ysihaoy** [flyway/flyway-play#22]
We are thinking to use Flyway as Play evolutions can't let us run db migration before starting sever.

After I had a look this plugin, it seems quite similar to Play evolutions. 

My question is if I use this plugin, can I still use some SBT tasks Flyway supported in this http://flywaydb.org/documentation/sbt/

Thanks.

**Comment by ysihaoy** [comment]
Anyone could know that?

**Comment by ssanj** [comment]
Yes, you can. The Flyway SBT plugin works with SBT/Activator and this module doesn't stop you from using it.

**Comment by tototoshi** [comment]
@ssanj thanks
