### ISSUE TITLE
Apply migrations on specific Database object

### ISSUE THREAD

**Issue by swsnr** [flyway/flyway-play#28]
Is there a way to apply Flyway migrations on a specific `Database` objects, such as one that comes from `Databases.withDatabase`?

**Comment by tototoshi** [comment]
No, flyway-play is independent on database API of Play.

**Comment by lunaryorn** [comment]
@tototoshi Well, so I presume there's no way to get a list of all migrations for a particular database from flyway-play either, so that we can manually apply these?

**Comment by tototoshi** [comment]
@lunaryorn Applying migration on each database can be done from admin page (http://localhost:9000/@flyway).
or does "manually apply" mean "programmatically apply"?

**Comment by lunaryorn** [comment]
Yes, the latter.  Sorry my comment was really misleading 😔

**Comment by tototoshi** [comment]
No problem. I'm trying to fix it and want you to review it. Please wait some time.
