### ISSUE TITLE
Play 2.6 support

### ISSUE THREAD

**Issue by lloydmeta** [flyway/flyway-play#46]
[Play 2.6 is coming soon](https://www.lightbend.com/blog/lightbend-podcast-play-2-6-is-coming-and-its-faster-than-ever) and `2.6.0-M5` is available.

Is there any chance of a pre-release / snapshot version of flyway-play for Play 2.6 being published so devs can get ready?

**Comment by yeryomenkom** [comment]
+1

**Comment by xuwei-k** [comment]
http://repo1.maven.org/maven2/org/flywaydb/flyway-play_2.12/4.0.0/

**Comment by lloydmeta** [comment]
Thanks @tototoshi and @xuwei-k
