### ISSUE TITLE
What's the preferred way to handle subprojects with flyway-play ?

### ISSUE THREAD

**Issue by woyzeck** [flyway/flyway-play#52]
I'm kind of lost when it comes to handling sub-projects.

Should the migration scripts be placed in the sub-project where they belong to, or in a central (root) project ?
How would you apply the migrations in such scenario ?

**Comment by tototoshi** [comment]
Flyway-play works in either way. I think that it depends on the situation.

In one of my projects, I'm using flyway in the core subproject and flyway-play in the web application project that depends on the core subproject. And migration scripts is placed in core and shared by both subprojects.
