### ISSUE TITLE
Add new configuration parameter - dbFolder

### ISSUE THREAD

**Issue by gomes-rocket** [flyway/flyway-play#60]
Hi,
I have play configured to deal with multiple modules. My migration folder structure is based on module names.
It would be very useful to add a new configuration parameter, called for instance dbFolder. That parameter would be used to set the path to the DB migrations.

Currenlty the path to the files are under
**migrationFilesLocation = s"$flywayPrefixToMigrationScript/$dbName"**

It would be useful to have like an alias, if configuration is set, use configuration value otherwise use dbName. If would a minor change
**migrationFilesLocation = s"$flywayPrefixToMigrationScript/configuration.dbFolder"**

With this new parameter i could have like this in my setup:

**db.finance_ke.url = ....
db.finance_ke.migration.dbFolder = finance
db.finance_ma.url = ....
db.finance_ma.migration.dbFolder = finance
db.finance_eg_url = ....
db.finance_eg.migration.dbFolder = finance**

So, i could have

+---- /conf
+--------- /db
+------------- /migration
+---------------------/finance
+---------------------------V1__testing.sql

What do you think? I need help on having folder name, not matching the DB name.
Check PR here #61

**Comment by tototoshi** [comment]
Fixed by https://github.com/flyway/flyway-play/pull/61
