### ISSUE TITLE
Flyway 5.2.x (broken)

### ISSUE THREAD

**Issue by nafg** [flyway/flyway-play#63]
I hit the following issues:

1) Runtime error due to `org.flywaydb.core.internal.util.jdbc.DriverDataSource` being renamed to `org.flywaydb.core.internal.jdbc.DriverDataSource` ("util" removed from FQN)
2) Runtime warning that using the Flyway constructor and mutators is deprecated; instead use the `Flyway.configure` fluent builder.

**Comment by tototoshi** [comment]
Thank you for the information. I addressed 1 and also planned for 2.

**Comment by nafg** [comment]
Thanks!
Is it published?
