### ISSUE TITLE
Play 2.7.0 support

### ISSUE THREAD

**Issue by mgilbertnz** [flyway/flyway-play#66]
Play 2.7.0 has removed web commands and this has broken flyway-play

Please see this issue for more info.

https://github.com/playframework/playframework/issues/9107

**Comment by tototoshi** [comment]
Published flyway-play 5.3.0. Please try it.

**Comment by mgilbertnz** [comment]
Hey,

Thanks for the release.  Unfortunately it appears that it doesn't fix the issue.

I checked out this repo
```
sbt
> project playapp
> run
```

In browser go to:  `http://localhost:9000`

When you try to execute the migration it does not execute, it reload the page immediately.

**Comment by tototoshi** [comment]
Sorry, that's right. I will investigate

**Comment by tototoshi** [comment]
Thanks, I understand the issue of https://github.com/playframework/playframework/issues/9107
and made a commit.
https://github.com/flyway/flyway-play/commit/eb3505e87cb380662193a6d0caccac407a349dfb 

Also, I published 5.3.1-SNAPSHOT to the snapshot repository of Sonatype. Could you try it?

**Comment by mgilbertnz** [comment]
Thanks for the quick turn around.  This has fixed it!

I'll close the issue.
