### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by xuwei-k** [flyway/flyway-play#71]
playframework 2.7.3 will support Scala 2.13

**Comment by xuwei-k** [comment]
https://github.com/flyway/flyway-play/pull/73

**Comment by jopecko** [comment]
When did you think you'll be ready to push out a 2.13 release?

**Comment by xuwei-k** [comment]
https://repo1.maven.org/maven2/org/flywaydb/flyway-play_2.13/
