### ISSUE TITLE
Flyway 6 support

### ISSUE THREAD

**Issue by arteme** [flyway/flyway-play#80]
Flyway 6 has been released in August 2019. It features support for many new DB version such as PostgreSQL 11 and 12. `flyway-play` should to be updated to support Flyway 6.

**Comment by nafg** [comment]
According to README it is. But now we need Flyway 7 support.

**Comment by nafg** [comment]
According to README it is. But now we need Flyway 7 support.

**Comment by tototoshi** [comment]
I will close this issue since it’s already done
