### ISSUE TITLE
Maven "flyway-play" may require scala postfix?

### ISSUE THREAD

**Issue by chris-james-git** [flyway/flyway-play#91]
I've just "fixed" a problem I was having when trying to add flyway-play to my Play instance. I had been using the following in my build.sbt as instructed:

`libraryDependencies ++= Seq(
  "org.flywaydb" %% "flyway-play" % "6.0.0"
)`

However, apparently "flyway-play" is not a maven path. Instead it appears that you also need to add "_[scala version]", so for example I am using Scala 2.13 so it became:

`libraryDependencies ++= Seq(
  "org.flywaydb" %% "flyway-play_2.13" % "6.0.0"
)`

Without that change, sbt was unable to build the application due to being unable to locate the library.

**Comment by tototoshi** [comment]
I would like you to check your configuration. The difference between % and %% is important.
Does it look like this?

```scala
libraryDependencies ++= Seq( "org.flywaydb" % "flyway-play_2.13" % "6.0.0" )
```


The following two are equivalent in build.sbt.

````scala
libraryDependencies ++= Seq( "org.flywaydb" %% "flyway-play" % "6.0.0" )

libraryDependencies ++= Seq( "org.flywaydb" % "flyway-play_2.13" % "6.0.0" )
````
